# PLEASE ENABLE THE GITLAB_HOME VARIABLE == export GITLAB_HOME=/srv/gitlab
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.healthierclinic.com'
    environment:
      GITLAB_ROOT_EMAIL: "admin@healthierclinic.com"
      GITLAB_ROOT_PASSWORD: "Youshouldchangethispassword"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - './gitlab/gitlab.rb:/etc/gitlab/gitlab.rb'
    shm_size: '256m'
    networks:
      mynet:
        ipv4_address: 172.19.0.2
  dns-bind:
    container_name: dns-bind
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Sao_Paulo
    ports:
      - "192.168.0.9:53:53/tcp"
      - "192.168.0.9:53:53/udp"
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/cache:/var/cache/bind
      - ./bind9/records:/var/lib/bind

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16