# PLEASE ENABLE SET THE GITLAB_HOME VARIABLE
#echo 'export GITLAB_HOME=/srv/gitlab' >> ~/.bashrc
#source ~/.bashrc
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.healthierclinic.com'
    ports:
      - '8080:80'
      - '8443:443'
      - '22:22'
    dns:
      - 172.19.0.3
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - './gitlab.rb:/etc/gitlab/gitlab.rb'
      - './resolv.conf:/etc/resolv.conf'
    shm_size: '256m'
    networks:
      mysharednet:
        ipv4_address: 172.19.0.2

networks:
      mysharednet:
        external: true
        