# PLEASE ENABLE THE GITLAB_HOME VARIABLE == export GITLAB_HOME=/srv/gitlab
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.healthierclinic.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - './gitlab.rb:/etc/gitlab/gitlab.rb'
    shm_size: '256m'
    networks:
      mynet:
        ipv4_address: 172.19.0.2

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16