services:
  bind:
    container_name: bind
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Sao_Paulo
    ports:
      - "192.168.0.11:53:53/tcp"
      - "192.168.0.11:53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
      - ./run:/run/named
    networks:
      mysharednet:
        ipv4_address: 172.19.0.3

networks:
      mysharednet:
        external: true
