concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner1"
  url = "https://gitlab.healthierclinic.com"
  id = 11
  token = "glrt-t3_1Eoe7B7JfLySpb4E4-1y"
  token_obtained_at = 2025-02-22T07:30:20Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/etc/ssl:/etc/ssl", "/cache"]
    network_mode = "mysharednet"
    shm_size = 0
    network_mtu = 0